[2025-02-02T08:22:38.933+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T08:22:38.943+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp_fetch_mongo.fetch_from_mongo manual__2025-02-02T08:22:37.028909+00:00 [queued]>
[2025-02-02T08:22:38.948+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp_fetch_mongo.fetch_from_mongo manual__2025-02-02T08:22:37.028909+00:00 [queued]>
[2025-02-02T08:22:38.948+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-02T08:22:38.953+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_from_mongo> on 2025-02-02 08:22:37.028909+00:00
[2025-02-02T08:22:38.958+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-02T08:22:38.959+0000] {standard_task_runner.py:72} INFO - Started process 70 to run task
[2025-02-02T08:22:38.959+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp_fetch_mongo', 'fetch_from_mongo', 'manual__2025-02-02T08:22:37.028909+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpj619eq13']
[2025-02-02T08:22:38.960+0000] {standard_task_runner.py:105} INFO - Job 126: Subtask fetch_from_mongo
[2025-02-02T08:22:38.995+0000] {task_command.py:467} INFO - Running <TaskInstance: idp_fetch_mongo.fetch_from_mongo manual__2025-02-02T08:22:37.028909+00:00 [running]> on host 3aa1f743f988
[2025-02-02T08:22:39.043+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp_fetch_mongo' AIRFLOW_CTX_TASK_ID='fetch_from_mongo' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T08:22:37.028909+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-02T08:22:37.028909+00:00'
[2025-02-02T08:22:39.046+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-02T08:22:39.046+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-02T08:22:39.046+0000] {logging_mixin.py:190} INFO - Current task name:fetch_from_mongo state:running start_date:2025-02-02 08:22:38.944184+00:00
[2025-02-02T08:22:39.047+0000] {logging_mixin.py:190} INFO - Dag name:idp_fetch_mongo and current dag run status:running
[2025-02-02T08:22:39.047+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T08:22:39.058+0000] {base.py:84} INFO - Retrieving connection 'mongoid'
[2025-02-02T08:22:39.059+0000] {logging_mixin.py:190} INFO - Error fetching from MongoDB: Bad database name "/admin:***@cluster0"
[2025-02-02T08:22:39.060+0000] {python.py:240} INFO - Done. Returned value was: []
[2025-02-02T08:22:39.070+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T08:22:39.071+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp_fetch_mongo, task_id=fetch_from_mongo, run_id=manual__2025-02-02T08:22:37.028909+00:00, execution_date=20250202T082237, start_date=20250202T082238, end_date=20250202T082239
[2025-02-02T08:22:39.075+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-02T08:22:39.075+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-02T08:22:39.075+0000] {logging_mixin.py:190} INFO - Dag name:idp_fetch_mongo queued_at:2025-02-02 08:22:37.040723+00:00
[2025-02-02T08:22:39.076+0000] {logging_mixin.py:190} INFO - Task hostname:3aa1f743f988 operator:PythonOperator
[2025-02-02T08:22:39.104+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T08:22:39.114+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T08:22:39.115+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
